### ISSUE TITLE
Display item upgrade track next to item level

### ISSUE THREAD

**Issue by j-reher** [daphii/ReadyGear#16]
It would be a very convenient overview to show an item's upgrade track and possibly it's upgrade stage (as in, Vet 5/8) next to its item level, as this helps determine if it could be improved or if one would have to rely on a drop.

The add-on https://www.curseforge.com/wow/addons/item-upgrade-quality-icons uses the crafting quality items to indicate upgrade track in tooltips, that could be a good way to show it.

**Comment by daphii** [comment]
I think thats a great idea! will add that in for 0.1.3!

**Comment by daphii** [comment]
I think it makes the most sense to me to add a custom upgrade stage 1, so that the in-game icons are used for 2-6, so to maintain the pentagon gem shape as shorthand for 'best'.

**Comment by j-reher** [comment]
That'll work too, my only issue is that it will create discrepancies with other addons that use the purple hexagon for myth track.

**Comment by daphii** [comment]
Perhaps that's a good setting to have. Let people toggle between either set!

**Comment by j-reher** [comment]
That's certainly going to work.

Knowing that the hexagon is coded as "ChatIcon-Quality-Tier6" makes me feel like it may be used at some point for particularly extravagant crafts.

**Comment by daphii** [comment]
oh is it? I thought it was custom!

I'm not able to get it for some reason!
![image](https://github.com/user-attachments/assets/2e5260c3-c956-43fd-ac34-95a3c1108b7b)
![image](https://github.com/user-attachments/assets/0df38cda-b941-4180-b67b-3856b8afe21b)

**Comment by j-reher** [comment]
Ah, nevermind then. Good job then to whoever made it, looks perfect!
