### ISSUE TITLE
Show Item slot in list

### ISSUE THREAD

**Issue by j-reher** [daphii/ReadyGear#17]
Hard-coding the equipment slot of all items on the left side of the table table will make it easier to read -- it's easier to see "I need to socket my helmet" than "I need to socket [insert long item name]".

**Comment by daphii** [comment]
```
603 | Cloak | Myonic Wrap | Enchant Missing! | No Gem Slot

It would be easier when shopping for enchants to see at a glance what slot I'm looking for an enchant for!
```
from @evelynsays

**Comment by daphii** [comment]
I'm looking at this today, and i feel like a few column different orders make sense to me
```
603 | Cloak | Symbol | Myonic Wrap | Enchant Missing! | No Gem Slot | Durability 
```
```
Durability | 603 | Symbol | Myonic Wrap | Cloak | Enchant Missing! | No Gem Slot
```
```
Symbol | 603 | Myonic Wrap | Durability | Cloak | Enchant Missing! | No Gem Slot
```

I like the item slot name in the middle, as to me it reads a bit more like a T chart.
```
Item Info | Item Slot | Item Enhancements
```
this way you wont find yourself having to try to follow the line all the way from "missing gem" all the way over to slot name when dealing with a mid list entry!
