### ISSUE TITLE
Open on Join Group

### ISSUE THREAD

**Issue by daphii** [daphii/ReadyGear#4]
add an option to have the window appear when a readycheck is triggered.

**Comment by j-reher** [comment]
It may be more helpful to open whenever joining a raid group instead of every single ready check. By the a time ready check goes out, it is usually too late to fix any of the issues you're tracking.

**Comment by daphii** [comment]
Great point! My initial thought with the on ready check was more for the tattling / confirmation message in chat!

As for prep, opening on joining a group is a brilliant idea!!
